# Change build command to 'make build-teamsafe' to hide team folder
[build]
  command = "make build"
  publish = "_site/"

[template.environment]
  APP_KEY = "Change me for your Airtable API Key"
  APP_ID = "Change me for your Airtable APP ID"